name: caritas
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  lottie: ^3.1.0
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  video_player: ^2.1.15
  intl: ^0.19.0
  table_calendar: ^3.1.1
  syncfusion_flutter_calendar: ^25.1.41
  image_picker: ^1.1.1
  flutter_cupernino_bottom_sheet: ^1.0.8
  awesome_notifications: ^0.9.3+1
  mysql_client: ^0.0.27
  mysql1: ^0.20.0
  flutter_chat_ui: ^1.6.13
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  carousel_slider: ^4.0.0
  open_filex: ^4.4.0
  file_picker: ^8.0.3
  #geolocator: ^12.0.0
  #geocoding: ^3.0.0
  #google_maps_flutter: ^2.7.0
  #google_maps_place_picker_mb: ^3.1.2

  #location: ^6.0.2
  #url_launcher: ^6.0.9

  google_maps_flutter: ^2.0.8

  geolocator: ^12.0.0

  flutter_google_places: ^0.3.0

  awesome_snackbar_content: ^0.1.3



  # firebase packages
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7
  
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  uuid: ^3.0.7


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0
  


flutter:
  
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/videos/
    - assets/caritas_logo.png
    - assets/pp.jpeg
    - assets/fruits.jpeg
    - assets/vegetables.jpeg
    - assets/desserts.jpeg
    - assets/grains.jpeg
    - assets/sweets_snacks.jpeg
    - assets/beverages.jpeg
    - assets/herbes_spices.jpeg
    - assets/baked_goods.jpeg
    - assets/fat_oil.jpeg
    - assets/malnutrition.jpeg
    - assets/education.jpeg
    - assets/emotion.jpeg
    - assets/images/asian_girl.jpg
    - assets/images/orphanage1.jpeg
    - assets/images/orphanage2.jpeg
    - assets/images/orphanage3.jpeg
    - assets/restaurant/restaurantA.jpeg
    - assets/restaurant/restaurantB.jpeg
    - assets/restaurant/restaurantC.jpeg
    - assets/grocery/supermarket1.jpeg
    - assets/grocery/supermarket2.jpeg
    - assets/grocery/supermarket3.jpeg
    - assets/restaurant/menu1.jpeg
    - assets/restaurant/menu2.jpeg
    - assets/restaurant/menu3.jpeg
    - assets/images/old_man.jpg
    - assets/images/african_child.jpg
    - assets/images/children.jpg
    - assets/images/wheelchair.jpg
    - assets/images/african2.jpg
    - assets/images/welcome.png
    - assets/videos/orphanage1.mp4
    - assets/videos/orphanage2.mp4
    - assets/videos/orphanage3.mp4
    - assets/images/
    
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

 
  # fonts:
  #   - family: Schyler
  #      fonts: 
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:

  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
   